import type { NewsArticle } from "@/lib/news";
import data from "@/lib/newsArchive.json";

/**
 * 556 articles carried over from the old WordPress site, generated by
 * scripts/import-news-archive.cjs from scripts/data/yefi-posts-export.csv —
 * edit the export or the script and re-run it rather than this file.
 *
 * Cover photos are placeholders: the real ones live on yefi.org, which this
 * pipeline has no network access to fetch from.
 * scripts/data/news-archive-image-sources.json keeps the original URL per
 * slug for a later backfill pass.
 */
export const archiveNewsArticles = data as NewsArticle[];
