/**
 * Every YEF chapter country, with the lat/lon the network globe plots it at.
 * Kept in lockstep with `countries` in `@/lib/i18n/countries` — same codes,
 * same count — but this list only needs to survive as marker positions, not
 * carry locales/regions, so it stays its own small file.
 */
export type ChapterCountry = {
  code: string;
  name: string;
  lat: number;
  lon: number;
};

export const CHAPTER_COUNTRIES: ChapterCountry[] = [
  { code: "br", name: "Brazil", lat: -15.8, lon: -47.9 },
  { code: "ca", name: "Canada", lat: 45.4, lon: -75.7 },
  { code: "co", name: "Colombia", lat: 4.6, lon: -74.1 },
  { code: "fr", name: "France", lat: 48.9, lon: 2.3 },
  { code: "de", name: "Germany", lat: 52.5, lon: 13.4 },
  { code: "in", name: "India", lat: 28.6, lon: 77.2 },
  { code: "id", name: "Indonesia", lat: -6.2, lon: 106.8 },
  { code: "it", name: "Italy", lat: 41.9, lon: 12.5 },
  { code: "jp", name: "Japan", lat: 35.7, lon: 139.7 },
  { code: "ke", name: "East Africa Federation", lat: -1.3, lon: 36.8 },
  { code: "kr", name: "South Korea", lat: 37.6, lon: 127 },
  { code: "mx", name: "Mexico", lat: 19.4, lon: -99.1 },
  { code: "ng", name: "Nigeria", lat: 9.1, lon: 7.4 },
  { code: "au", name: "Australia", lat: -35.3, lon: 149.1 },
  { code: "ru", name: "Russia", lat: 55.8, lon: 37.6 },
  { code: "za", name: "South Africa", lat: -25.7, lon: 28.2 },
  { code: "es", name: "Spain", lat: 40.4, lon: -3.7 },
  { code: "tr", name: "Türkiye", lat: 39.9, lon: 32.9 },
  { code: "gb", name: "United Kingdom", lat: 51.5, lon: -0.1 },
  { code: "us", name: "United States", lat: 38.9, lon: -77 },
  { code: "ao", name: "Angola", lat: -8.8, lon: 13.2 },
  { code: "cm", name: "Cameroon", lat: 3.9, lon: 11.5 },
  { code: "cd", name: "Democratic Republic of the Congo", lat: -4.3, lon: 15.3 },
  { code: "et", name: "Ethiopia", lat: 9, lon: 38.7 },
  { code: "gh", name: "Ghana", lat: 5.6, lon: -0.2 },
  { code: "ci", name: "Côte d’Ivoire", lat: 6.8, lon: -5.3 },
  { code: "mg", name: "Madagascar", lat: -18.9, lon: 47.5 },
  { code: "mz", name: "Mozambique", lat: -25.9, lon: 32.6 },
  { code: "zm", name: "Zambia", lat: -15.4, lon: 28.3 },
  { code: "at", name: "Austria", lat: 48.2, lon: 16.4 },
  { code: "be", name: "Belgium", lat: 50.8, lon: 4.4 },
  { code: "cz", name: "Czechia", lat: 50.1, lon: 14.4 },
  { code: "sk", name: "Slovakia", lat: 48.1, lon: 17.1 },
  { code: "gr", name: "Greece", lat: 38, lon: 23.7 },
  { code: "hu", name: "Hungary", lat: 47.5, lon: 19 },
  { code: "nl", name: "Netherlands", lat: 52.1, lon: 5.3 },
  { code: "pl", name: "Poland", lat: 52.2, lon: 21 },
  { code: "pt", name: "Portugal", lat: 38.7, lon: -9.1 },
  { code: "ro", name: "Romania", lat: 44.4, lon: 26.1 },
  { code: "se", name: "Sweden", lat: 59.3, lon: 18.1 },
  { code: "ch", name: "Switzerland", lat: 46.9, lon: 7.4 },
  { code: "ua", name: "Ukraine", lat: 50.4, lon: 30.5 },
  { code: "do", name: "Dominican Republic", lat: 18.5, lon: -69.9 },
  { code: "ht", name: "Haiti", lat: 18.5, lon: -72.3 },
  { code: "ar", name: "Argentina", lat: -34.6, lon: -58.4 },
  { code: "cl", name: "Chile", lat: -33.4, lon: -70.6 },
  { code: "pe", name: "Peru", lat: -12, lon: -77 },
  { code: "kz", name: "Kazakhstan", lat: 51.2, lon: 71.4 },
  { code: "eg", name: "Egypt", lat: 30, lon: 31.2 },
  { code: "il", name: "Israel", lat: 31.8, lon: 35.2 },
  { code: "ae", name: "United Arab Emirates", lat: 24.5, lon: 54.4 },
  { code: "nz", name: "New Zealand", lat: -41.3, lon: 174.8 },
  { code: "fj", name: "Fiji", lat: -18.1, lon: 178.4 },
  { code: "bd", name: "Bangladesh", lat: 23.8, lon: 90.4 },
  { code: "np", name: "Nepal", lat: 27.7, lon: 85.3 },
  { code: "pk", name: "Pakistan", lat: 33.7, lon: 73.1 },
  { code: "my", name: "Malaysia", lat: 3.1, lon: 101.7 },
  { code: "mm", name: "Myanmar", lat: 19.7, lon: 96.1 },
  { code: "ph", name: "Philippines", lat: 14.6, lon: 121 },
  { code: "sg", name: "Singapore", lat: 1.35, lon: 103.8 },
  { code: "th", name: "Thailand", lat: 13.75, lon: 100.5 },
  { code: "vn", name: "Vietnam", lat: 21, lon: 105.8 },
  { code: "mn", name: "Mongolia", lat: 47.9, lon: 106.9 },
  { code: "tw", name: "Taiwan", lat: 25, lon: 121.5 },
  { code: "rw", name: "Rwanda", lat: -1.95, lon: 30.06 },
  { code: "gt", name: "Guatemala", lat: 14.6, lon: -90.5 },
  { code: "hn", name: "Honduras", lat: 14.1, lon: -87.2 },
  { code: "lk", name: "Sri Lanka", lat: 6.9, lon: 79.9 },
];
