/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    members: MemberAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    'photo-events': PhotoEvent;
    media: Media;
    users: User;
    members: Member;
    resources: Resource;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'photo-events': PhotoEventsSelect<false> | PhotoEventsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Member;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface MemberAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Build a page by stacking sections. Drag a section by its handle to reorder it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * For the admin list only; not shown on the site.
   */
  title: string;
  /**
   * Which page of the country's site this lays out.
   */
  route:
    | 'home'
    | 'who-we-are'
    | 'who-we-are/welcome'
    | 'who-we-are/mission'
    | 'who-we-are/statement-of-faith'
    | 'who-we-are/history'
    | 'who-we-are/membership'
    | 'who-we-are/staff-executive-committee'
    | 'get-involved'
    | 'get-involved/apply'
    | 'get-involved/campus-evangelism'
    | 'get-involved/campus-evangelism/apply'
    | 'get-involved/chapter-affiliation'
    | 'get-involved/leadership-retreats'
    | 'get-involved/volunteer'
    | 'news'
    | 'network'
    | 'donate'
    | 'contact'
    | 'join'
    | 'login'
    | 'reaching-the-campus'
    | 'resources'
    | 'sharing-the-gospel'
    | 'submit-your-story'
    | 'what-is-evangelical'
    | 'yef-mission-school'
    | 'yef-mission-school/apply';
  country:
    | 'int'
    | 'ao'
    | 'ar'
    | 'au'
    | 'at'
    | 'bd'
    | 'be'
    | 'br'
    | 'cm'
    | 'ca'
    | 'cl'
    | 'co'
    | 'ci'
    | 'cz'
    | 'cd'
    | 'do'
    | 'ke'
    | 'eg'
    | 'et'
    | 'fj'
    | 'fr'
    | 'de'
    | 'gh'
    | 'gr'
    | 'gt'
    | 'ht'
    | 'hn'
    | 'hu'
    | 'in'
    | 'id'
    | 'il'
    | 'it'
    | 'jp'
    | 'kz'
    | 'mg'
    | 'my'
    | 'mx'
    | 'mn'
    | 'mz'
    | 'mm'
    | 'np'
    | 'nl'
    | 'nz'
    | 'ng'
    | 'pk'
    | 'pe'
    | 'ph'
    | 'pl'
    | 'pt'
    | 'ro'
    | 'ru'
    | 'rw'
    | 'sg'
    | 'sk'
    | 'za'
    | 'kr'
    | 'es'
    | 'lk'
    | 'se'
    | 'ch'
    | 'tw'
    | 'th'
    | 'tr'
    | 'ua'
    | 'ae'
    | 'gb'
    | 'us'
    | 'vn'
    | 'zm';
  /**
   * This page is listed so every real page of the site shows up here. Its banner photo, heading, and intro line below are always editable; the sections underneath are edited as blocks in Layout below.
   */
  builtIn?: boolean | null;
  /**
   * Overrides this page's banner photo, heading, and intro line. Leave a field empty to keep what the page ships with in code.
   */
  header?: {
    image?: (number | null) | Media;
    heading?: string | null;
    intro?: string | null;
  };
  /**
   * Sections render top to bottom in this order, below the banner. Removing one falls back to nothing — leave it in place to keep it. Pick a block under “Generic sections” to add a new section to a built-in page.
   */
  layout?:
    | (
        | {
            /**
             * Shown in this order, cycling automatically.
             */
            slides?:
              | {
                  image: number | Media;
                  /**
                   * A line break here breaks the headline.
                   */
                  heading: string;
                  body: string;
                  /**
                   * Optional — leave both empty for no button.
                   */
                  buttonLabel?: string | null;
                  buttonHref?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            image?: (number | null) | Media;
            eyebrow?: string | null;
            heading?: string | null;
            /**
             * Set in the italic serif, e.g. “young”.
             */
            headingAccent?: string | null;
            lead?: string | null;
            body?: string | null;
            stats?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'about';
          }
        | {
            eyebrow?: string | null;
            verse?: string | null;
            /**
             * The closing phrase, set in the italic serif.
             */
            verseAccent?: string | null;
            reference?: string | null;
            columns?:
              | {
                  body: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mission';
          }
        | {
            eyebrow?: string | null;
            /**
             * Wrap a phrase in **double asterisks** to set it in the italic serif.
             */
            heading?: string | null;
            items?:
              | {
                  /**
                   * Optional — leave empty for no number shown.
                   */
                  number?: string | null;
                  name: string;
                  body: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'proof';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            body?: string | null;
            buttonLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'signup';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'campusFinder';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'getInvolved';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'giving';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'movement';
          }
        | {
            image?: (number | null) | Media;
            heading?: string | null;
            body?: string | null;
            /**
             * Shown after the bolded label “Mission Statement:” in the hero.
             */
            missionBody?: string | null;
            portrait?: (number | null) | Media;
            /**
             * The short pull-quote over the portrait.
             */
            quote?: string | null;
            /**
             * e.g. “- Dr. Mark Wagner, President of YEF”.
             */
            signature?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'whoWeAreHero';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            /**
             * Always the three cards in this order (Welcome, Membership, Statement of Faith) — only their words and photo are editable here.
             */
            cards?:
              | {
                  image?: (number | null) | Media;
                  /**
                   * A line break here breaks the label.
                   */
                  eyebrow?: string | null;
                  title?: string | null;
                  cta?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'introCards';
          }
        | {
            heading?: string | null;
            body?: string | null;
            image?: (number | null) | Media;
            /**
             * Always the same three pillars, in order — only the title and body are editable; the icon is fixed.
             */
            pillars?:
              | {
                  title?: string | null;
                  body?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'visionMission';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'storiesNews';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'missionSchoolCta';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            /**
             * Shown one after another, in this order.
             */
            paragraphs?:
              | {
                  body: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'genericText';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            cards?:
              | {
                  title: string;
                  body: string;
                  /**
                   * Optional — an italic pull-quote under the card body.
                   */
                  quote?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'genericCards';
          }
        | {
            image: number | Media;
            imageAlt?: string | null;
            imageSide?: ('left' | 'right') | null;
            heading: string;
            body: string;
            /**
             * Optional — leave both empty for no button.
             */
            buttonLabel?: string | null;
            buttonHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'genericImageText';
          }
        | {
            /**
             * Exactly three photos: one large, two stacked beside it.
             */
            images?:
              | {
                  image: number | Media;
                  alt?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'genericGallery';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            stats?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'genericStats';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            items?:
              | {
                  year: string;
                  title: string;
                  body: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'genericTimeline';
          }
        | {
            heading: string;
            body?: string | null;
            buttonLabel: string;
            buttonHref: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'genericCta';
          }
        | {
            quote: string;
            reference?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'genericQuote';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Which country site owns this file.
   */
  country:
    | 'int'
    | 'ao'
    | 'ar'
    | 'au'
    | 'at'
    | 'bd'
    | 'be'
    | 'br'
    | 'cm'
    | 'ca'
    | 'cl'
    | 'co'
    | 'ci'
    | 'cz'
    | 'cd'
    | 'do'
    | 'ke'
    | 'eg'
    | 'et'
    | 'fj'
    | 'fr'
    | 'de'
    | 'gh'
    | 'gr'
    | 'gt'
    | 'ht'
    | 'hn'
    | 'hu'
    | 'in'
    | 'id'
    | 'il'
    | 'it'
    | 'jp'
    | 'kz'
    | 'mg'
    | 'my'
    | 'mx'
    | 'mn'
    | 'mz'
    | 'mm'
    | 'np'
    | 'nl'
    | 'nz'
    | 'ng'
    | 'pk'
    | 'pe'
    | 'ph'
    | 'pl'
    | 'pt'
    | 'ro'
    | 'ru'
    | 'rw'
    | 'sg'
    | 'sk'
    | 'za'
    | 'kr'
    | 'es'
    | 'lk'
    | 'se'
    | 'ch'
    | 'tw'
    | 'th'
    | 'tr'
    | 'ua'
    | 'ae'
    | 'gb'
    | 'us'
    | 'vn'
    | 'zm';
  /**
   * Describe the photo for screen readers and for when it fails to load.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tile?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Posts appear on the News page. Tick “Show on the home page” to also put one in the Around the Movement strip.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * The country site this post belongs to. Its editors own it wherever else it appears.
   */
  country:
    | 'int'
    | 'ao'
    | 'ar'
    | 'au'
    | 'at'
    | 'bd'
    | 'be'
    | 'br'
    | 'cm'
    | 'ca'
    | 'cl'
    | 'co'
    | 'ci'
    | 'cz'
    | 'cd'
    | 'do'
    | 'ke'
    | 'eg'
    | 'et'
    | 'fj'
    | 'fr'
    | 'de'
    | 'gh'
    | 'gr'
    | 'gt'
    | 'ht'
    | 'hn'
    | 'hu'
    | 'in'
    | 'id'
    | 'il'
    | 'it'
    | 'jp'
    | 'kz'
    | 'mg'
    | 'my'
    | 'mx'
    | 'mn'
    | 'mz'
    | 'mm'
    | 'np'
    | 'nl'
    | 'nz'
    | 'ng'
    | 'pk'
    | 'pe'
    | 'ph'
    | 'pl'
    | 'pt'
    | 'ro'
    | 'ru'
    | 'rw'
    | 'sg'
    | 'sk'
    | 'za'
    | 'kr'
    | 'es'
    | 'lk'
    | 'se'
    | 'ch'
    | 'tw'
    | 'th'
    | 'tr'
    | 'ua'
    | 'ae'
    | 'gb'
    | 'us'
    | 'vn'
    | 'zm';
  /**
   * Where this post is published. A post shown elsewhere is still edited here, by this country's team.
   */
  audience: 'own' | 'some' | 'all';
  /**
   * The other country sites that also show this post.
   */
  distributeTo?:
    | (
        | 'int'
        | 'ao'
        | 'ar'
        | 'au'
        | 'at'
        | 'bd'
        | 'be'
        | 'br'
        | 'cm'
        | 'ca'
        | 'cl'
        | 'co'
        | 'ci'
        | 'cz'
        | 'cd'
        | 'do'
        | 'ke'
        | 'eg'
        | 'et'
        | 'fj'
        | 'fr'
        | 'de'
        | 'gh'
        | 'gr'
        | 'gt'
        | 'ht'
        | 'hn'
        | 'hu'
        | 'in'
        | 'id'
        | 'il'
        | 'it'
        | 'jp'
        | 'kz'
        | 'mg'
        | 'my'
        | 'mx'
        | 'mn'
        | 'mz'
        | 'mm'
        | 'np'
        | 'nl'
        | 'nz'
        | 'ng'
        | 'pk'
        | 'pe'
        | 'ph'
        | 'pl'
        | 'pt'
        | 'ro'
        | 'ru'
        | 'rw'
        | 'sg'
        | 'sk'
        | 'za'
        | 'kr'
        | 'es'
        | 'lk'
        | 'se'
        | 'ch'
        | 'tw'
        | 'th'
        | 'tr'
        | 'ua'
        | 'ae'
        | 'gb'
        | 'us'
        | 'vn'
        | 'zm'
      )[]
    | null;
  title: string;
  /**
   * The web address for this post, e.g. yef-tonga-romans.
   */
  slug: string;
  category: 'News' | 'Story' | 'Event';
  publishedAt: string;
  image: number | Media;
  /**
   * The one or two lines shown on the News card.
   */
  excerpt: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Adds this post to the Around the Movement strip. The three most recent ticked posts are shown.
   */
  showOnHome?: boolean | null;
  /**
   * The small caps line above the title on the home page, e.g. FIELD REPORT. Defaults to the category.
   */
  homeEyebrow?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * A batch of photos from one event. The first photo is used as the cover tile.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photo-events".
 */
export interface PhotoEvent {
  id: number;
  country:
    | 'int'
    | 'ao'
    | 'ar'
    | 'au'
    | 'at'
    | 'bd'
    | 'be'
    | 'br'
    | 'cm'
    | 'ca'
    | 'cl'
    | 'co'
    | 'ci'
    | 'cz'
    | 'cd'
    | 'do'
    | 'ke'
    | 'eg'
    | 'et'
    | 'fj'
    | 'fr'
    | 'de'
    | 'gh'
    | 'gr'
    | 'gt'
    | 'ht'
    | 'hn'
    | 'hu'
    | 'in'
    | 'id'
    | 'il'
    | 'it'
    | 'jp'
    | 'kz'
    | 'mg'
    | 'my'
    | 'mx'
    | 'mn'
    | 'mz'
    | 'mm'
    | 'np'
    | 'nl'
    | 'nz'
    | 'ng'
    | 'pk'
    | 'pe'
    | 'ph'
    | 'pl'
    | 'pt'
    | 'ro'
    | 'ru'
    | 'rw'
    | 'sg'
    | 'sk'
    | 'za'
    | 'kr'
    | 'es'
    | 'lk'
    | 'se'
    | 'ch'
    | 'tw'
    | 'th'
    | 'tr'
    | 'ua'
    | 'ae'
    | 'gb'
    | 'us'
    | 'vn'
    | 'zm';
  /**
   * Where this batch is published. A batch shown elsewhere is still edited here, by this country's team.
   */
  audience: 'own' | 'some' | 'all';
  /**
   * The other country sites that also show this batch.
   */
  distributeTo?:
    | (
        | 'int'
        | 'ao'
        | 'ar'
        | 'au'
        | 'at'
        | 'bd'
        | 'be'
        | 'br'
        | 'cm'
        | 'ca'
        | 'cl'
        | 'co'
        | 'ci'
        | 'cz'
        | 'cd'
        | 'do'
        | 'ke'
        | 'eg'
        | 'et'
        | 'fj'
        | 'fr'
        | 'de'
        | 'gh'
        | 'gr'
        | 'gt'
        | 'ht'
        | 'hn'
        | 'hu'
        | 'in'
        | 'id'
        | 'il'
        | 'it'
        | 'jp'
        | 'kz'
        | 'mg'
        | 'my'
        | 'mx'
        | 'mn'
        | 'mz'
        | 'mm'
        | 'np'
        | 'nl'
        | 'nz'
        | 'ng'
        | 'pk'
        | 'pe'
        | 'ph'
        | 'pl'
        | 'pt'
        | 'ro'
        | 'ru'
        | 'rw'
        | 'sg'
        | 'sk'
        | 'za'
        | 'kr'
        | 'es'
        | 'lk'
        | 'se'
        | 'ch'
        | 'tw'
        | 'th'
        | 'tr'
        | 'ua'
        | 'ae'
        | 'gb'
        | 'us'
        | 'vn'
        | 'zm'
      )[]
    | null;
  /**
   * e.g. Summer Mission Trip 2026 — Kenya.
   */
  title: string;
  /**
   * The web address for this batch, e.g. kenya-mission-trip-2026.
   */
  slug: string;
  publishedAt: string;
  photos: {
    image: number | Media;
    caption?: string | null;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * Who can sign in, which country sites they are responsible for, and which parts of those sites they may edit.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Shown next to their name in the admin. Anyone can set their own.
   */
  avatar?: (number | null) | Media;
  role: 'super' | 'region-admin' | 'country-admin' | 'editor';
  /**
   * The continents this person is responsible for. Every country in them falls into their scope.
   */
  regions?:
    | (
        | 'South America'
        | 'North America'
        | 'Europe'
        | 'South Asia'
        | 'Southeast Asia'
        | 'Asia-Pacific'
        | 'Africa'
        | 'Oceania'
        | 'Central America & Caribbean'
        | 'Commonwealth of Independent States'
        | 'Middle East & North Africa'
      )[]
    | null;
  /**
   * The country sites this person may edit. Ignored for super admins, who reach every country, and for continental admins, whose regions decide it.
   */
  countries?:
    | (
        | 'int'
        | 'ao'
        | 'ar'
        | 'au'
        | 'at'
        | 'bd'
        | 'be'
        | 'br'
        | 'cm'
        | 'ca'
        | 'cl'
        | 'co'
        | 'ci'
        | 'cz'
        | 'cd'
        | 'do'
        | 'ke'
        | 'eg'
        | 'et'
        | 'fj'
        | 'fr'
        | 'de'
        | 'gh'
        | 'gr'
        | 'gt'
        | 'ht'
        | 'hn'
        | 'hu'
        | 'in'
        | 'id'
        | 'il'
        | 'it'
        | 'jp'
        | 'kz'
        | 'mg'
        | 'my'
        | 'mx'
        | 'mn'
        | 'mz'
        | 'mm'
        | 'np'
        | 'nl'
        | 'nz'
        | 'ng'
        | 'pk'
        | 'pe'
        | 'ph'
        | 'pl'
        | 'pt'
        | 'ro'
        | 'ru'
        | 'rw'
        | 'sg'
        | 'sk'
        | 'za'
        | 'kr'
        | 'es'
        | 'lk'
        | 'se'
        | 'ch'
        | 'tw'
        | 'th'
        | 'tr'
        | 'ua'
        | 'ae'
        | 'gb'
        | 'us'
        | 'vn'
        | 'zm'
      )[]
    | null;
  /**
   * The parts of those sites this person may edit. Continental and country admins reach every section, so this applies to editors.
   */
  sections?: ('home' | 'who-we-are' | 'get-involved' | 'news' | 'network' | 'resources' | 'donate' | 'media')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Accounts for the Resources hub — approve a member here before they can sign in.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  name: string;
  role: 'member' | 'leader' | 'staff' | 'minister';
  /**
   * A member can't sign in until this is checked.
   */
  approved?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'members';
}
/**
 * Policies, training materials, forms, worship resources, and recorded messages shown on the Resources hub.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: number;
  title: string;
  description?: string | null;
  category: 'policy' | 'training' | 'forms' | 'worship' | 'media';
  kind: 'document' | 'audio' | 'video' | 'link';
  /**
   * Only used when Kind is set to External link.
   */
  externalUrl?: string | null;
  visibility: 'internal' | 'public';
  /**
   * Optional: a page section id (e.g. "leadership-training") to also surface this resource there.
   */
  relatedSlug?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'photo-events';
        value: number | PhotoEvent;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'resources';
        value: number | Resource;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'members';
        value: number | Member;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'members';
        value: number | Member;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  route?: T;
  country?: T;
  builtIn?: T;
  header?:
    | T
    | {
        image?: T;
        heading?: T;
        intro?: T;
      };
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              slides?:
                | T
                | {
                    image?: T;
                    heading?: T;
                    body?: T;
                    buttonLabel?: T;
                    buttonHref?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        about?:
          | T
          | {
              image?: T;
              eyebrow?: T;
              heading?: T;
              headingAccent?: T;
              lead?: T;
              body?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        mission?:
          | T
          | {
              eyebrow?: T;
              verse?: T;
              verseAccent?: T;
              reference?: T;
              columns?:
                | T
                | {
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        proof?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              items?:
                | T
                | {
                    number?: T;
                    name?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        signup?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              buttonLabel?: T;
              id?: T;
              blockName?: T;
            };
        campusFinder?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        getInvolved?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        giving?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        movement?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        whoWeAreHero?:
          | T
          | {
              image?: T;
              heading?: T;
              body?: T;
              missionBody?: T;
              portrait?: T;
              quote?: T;
              signature?: T;
              id?: T;
              blockName?: T;
            };
        introCards?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              cards?:
                | T
                | {
                    image?: T;
                    eyebrow?: T;
                    title?: T;
                    cta?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        visionMission?:
          | T
          | {
              heading?: T;
              body?: T;
              image?: T;
              pillars?:
                | T
                | {
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        storiesNews?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        missionSchoolCta?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        genericText?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              paragraphs?:
                | T
                | {
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        genericCards?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              cards?:
                | T
                | {
                    title?: T;
                    body?: T;
                    quote?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        genericImageText?:
          | T
          | {
              image?: T;
              imageAlt?: T;
              imageSide?: T;
              heading?: T;
              body?: T;
              buttonLabel?: T;
              buttonHref?: T;
              id?: T;
              blockName?: T;
            };
        genericGallery?:
          | T
          | {
              images?:
                | T
                | {
                    image?: T;
                    alt?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        genericStats?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        genericTimeline?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              items?:
                | T
                | {
                    year?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        genericCta?:
          | T
          | {
              heading?: T;
              body?: T;
              buttonLabel?: T;
              buttonHref?: T;
              id?: T;
              blockName?: T;
            };
        genericQuote?:
          | T
          | {
              quote?: T;
              reference?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  country?: T;
  audience?: T;
  distributeTo?: T;
  title?: T;
  slug?: T;
  category?: T;
  publishedAt?: T;
  image?: T;
  excerpt?: T;
  body?: T;
  showOnHome?: T;
  homeEyebrow?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photo-events_select".
 */
export interface PhotoEventsSelect<T extends boolean = true> {
  country?: T;
  audience?: T;
  distributeTo?: T;
  title?: T;
  slug?: T;
  publishedAt?: T;
  photos?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  country?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tile?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  avatar?: T;
  role?: T;
  regions?: T;
  countries?: T;
  sections?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  approved?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  category?: T;
  kind?: T;
  externalUrl?: T;
  visibility?: T;
  relatedSlug?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}